spring:
  datasource:
    url: jdbc:mysql://120.78.151.208:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: li15775063262
    driver-class-name: com.mysql.jdbc.Driver
